### ISSUE TITLE
ImportError: Java not found!

### ISSUE THREAD

**Issue by UnderCoverToni** [LordShadow505/Brawlhalla-Modding-Toolkit#1]
Most up-to-date java version installed, reinstalling it still causes issue.
"Traceback (most recent call last):
  File "SpriteExporterTool.py", line 3, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 391, in exec_module
  File "ffdec\__init__.py", line 42, in <module>
    raise ImportError("Java not found!")
ImportError: Java not found!"

**Comment by lmiol** [comment]
Yeah, the same
![image](https://github.com/user-attachments/assets/93f55e6c-5e6c-4e2c-baa3-343d0fda76cc)

**Comment by ghost** [comment]
here follow this: 
1. Find your Java installation directory:

First, you need to find where Java was installed. It's typically in a location like: C:\Program Files\Java\jdk-24.0.2 (the version number might be different). You can also find this by typing where java in the command prompt.

2. Set the JAVA_HOME environment variable:

Open Environment Variables: Search for "Environment Variables" in the Start Menu and select "Edit the system environment variables".

Click "Environment Variables...": In the System Properties window that opens, click the "Environment Variables..." button.

Create a new System Variable: Under "System variables", click "New...".

Enter the variable information:

Variable name: JAVA_HOME

Variable value: Enter the path to your JDK installation directory (e.g., C:\Program Files\Java\jdk-24.0.2).

Click OK.

3. Add Java to the Path variable:

Edit the Path variable: In the "System variables" section, find the "Path" variable and click "Edit...".

Add a new entry: Click "New" and add the following line: %JAVA_HOME%\bin

Click OK on all the windows to save the changes.

4. Restart your computer:

After making these changes, it's a good idea to restart your computer to ensure the changes take effect.
